tags: make _platform_tags public
pypa/packaging pull request #446
Opened 2021-07-12 17:38 UTC by FFY00

There are situations where we may need to look at the compatibly
platform versions. The best workaround for this would be using
compatible_tags and striping down the unecessary fields. There is
already a precedent for this, mac_platforms.

2021-07-13 21:06 UTC, brettcannon commented
I don't have a specific opposition to this idea, although I'm not sure what others think.

There's also no documentation to go with this, so if we choose to move forward with this then that will need to be rectified.

2021-07-13 21:12 UTC, pradyunsg commented
I'm fine with this as a concept -- although, as you said, documentation updates are likely necessary for this.

2021-07-16 22:12 UTC, brettcannon requested changes
Without reviewing the code (and assuming no objections come up to exposing this part of the API), doc changes are needed.

2021-07-16 23:08 UTC, FFY00 commented
No worries, I will do that next week.

2021-08-17 12:00 UTC, FFY00 commented
Friendly ping.

2021-08-23 20:00 UTC, brettcannon commented
Sorry, been sick. Refreshed my review request to get it back into my queue.

2021-08-23 20:09 UTC, FFY00 commented
No worries :smile:

2021-08-27 23:00 UTC, merged

2021-08-27 23:00 UTC, brettcannon commented
Thanks!