Document exceptions raised by functions in utils
pypa/packaging pull request #544
Opened 2022-05-06 13:59 UTC by MrMino

Closes #543.

Added `:raises ...:` clauses to documentation of functions from `packaging.utils`.
Class names have been given by their full import path, since they are not mentioned anywhere else in the documentation.

![image](https://user-images.githubusercontent.com/6691643/167147830-c78d2178-0fc8-4b27-a915-edfe096a003a.png)

![image](https://user-images.githubusercontent.com/6691643/167147928-9e63d661-7e7f-4392-bd8c-6a6b464de912.png)

2022-05-08 21:50 UTC, brettcannon commented
> Class names have been given by their full import path, since they are not mentioned anywhere else in the documentation.

Maybe we should change that? No reason to keep the exceptions undocumented.

2022-05-09 21:28 UTC, MrMino commented
Done. Here's the outcome:

Class names in raises clauses of `parse_...` functions are clickable

![image](https://user-images.githubusercontent.com/6691643/167501427-dd98e57a-7733-4a3f-90ca-9cc1388478ea.png)

Exception classes descriptions:

![image](https://user-images.githubusercontent.com/6691643/167501588-2e174e3a-2da1-48fc-a8ab-c886b2a5f8e5.png)

2022-05-19 10:50 UTC, MrMino commented
@brettcannon Anything else? Is the style / wording acceptable?

2022-05-20 22:39 UTC, brettcannon approved these changes

2022-05-20 22:40 UTC, brettcannon commented
> Anything else?

Nope, just me not being sick so I had time to review. 😅

2022-08-05 22:48 UTC, brettcannon requested changes
It's best to keep the docs for exceptions generic in case other code uses the exceptions in the future.

2022-08-05 22:48 UTC, brettcannon commented on docs/utils.rst
> +    filename that does not conform to `PEP 427`_
```suggestion
    Raised when a file name for a wheel is invalid.
```

2022-08-05 22:48 UTC, brettcannon commented on docs/utils.rst
> +    distribution (e.g. ``"foo1.0.tar.gz"`` instead of ``"foo-1.0.tar.gz"``).
```suggestion
    Raised a source distribution file name is considered invalid.
```

2022-08-05 22:49 UTC, brettcannon commented
Apologies for taking so long to get to this! Luckily 3.11.0.rc1 is getting cut today and I caught up to my review queue so I'm apparently only backed up until PRs created in May 😅.

2022-08-16 03:19 UTC, MrMino commented
Fixed. Thanks :).

2022-08-19 22:14 UTC, brettcannon approved these changes

2022-08-19 22:17 UTC, merged

2022-08-19 22:17 UTC, brettcannon commented
Thanks!