Raise InvalidRequirement from None
pypa/packaging pull request #593
Opened 2022-09-14 01:05 UTC by jack1142

Because `InvalidRequirement` is already raised with the whole message of ParseExceptionError, there's no much need to show the original exception which is an implementation detail anyway.
This PR improves the error message from:
```
Traceback (most recent call last):
  File "/home/ubuntu/work/packaging/packaging/requirements.py", line 40, in __init__
    req = _RequirementTuple(*parse_named_requirement(requirement_string))
  File "/home/ubuntu/work/packaging/packaging/_parser.py", line 90, in parse_named_requirement
    error_message="Expected semicolon (followed by markers) or end of string",
  File "/home/ubuntu/work/packaging/packaging/_tokenizer.py", line 111, in expect
    raise self.raise_syntax_error(message=error_message)
  File "/home/ubuntu/work/packaging/packaging/_tokenizer.py", line 140, in raise_syntax_error
    self.position,
packaging._tokenizer.ParseExceptionError: Expected semicolon (followed by markers) or end of string
at position 59:
    tomli @ https://github.com/hukkin/tomli/archive/master.zip; python_version < '3.11'
                                                               ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/work/packaging/packaging/requirements.py", line 42, in __init__
    raise InvalidRequirement(str(e))
packaging.requirements.InvalidRequirement: Expected semicolon (followed by markers) or end of string
at position 59:
    tomli @ https://github.com/hukkin/tomli/archive/master.zip; python_version < '3.11'
               
```
to:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/work/packaging/packaging/requirements.py", line 42, in __init__
    raise InvalidRequirement(str(e)) from None
packaging.requirements.InvalidRequirement: Expected semicolon (followed by markers) or end of string
at position 59:
    tomli @ https://github.com/hukkin/tomli/archive/master.zip; python_version < '3.11'
                                                               ^
```

I was considering doing the same with `InvalidMarker` *but* the error message there doesn't include all the information from the ParseExceptionError so this would make the error less useful.

2022-09-23 21:50 UTC, brettcannon commented
I think I would rather see the change be `raise InvalidRequirement from e` if there was a desire to suppress the duplicate output rather than toss out the parsing exception. At least for us having the full traceback helps debug issues.

2022-09-23 21:51 UTC, brettcannon commented
Do you have an opinion, @pradyunsg ?

2022-09-24 01:33 UTC, pradyunsg commented
I don’t have any opinion either way,

2022-09-24 01:42 UTC, jack1142 commented
I mostly made this PR because I found this traceback excessively big considering both exceptions convey the same amount of information. Still, I guess it would make more sense to use `raise InvalidRequirement(...) from exc` as `InvalidRequirement` is sort of a wrapper of the underlying exception and that's one of the cases this syntax is meant for. Just let me know what you want me to do and I'll update the PR if necessary.

2022-09-27 19:48 UTC, brettcannon commented
Then please use the `from exc` form.

2022-10-06 22:58 UTC, brettcannon requested changes

2022-10-06 22:58 UTC, brettcannon commented on packaging/requirements.py
> +            raise InvalidRequirement(str(e)) from e
I'm not sure if repeating the string from `e` gets us anything. I think raising the appropriate exception is important for `except` clauses, but a person looking at the output can look at the traceback to see what ultimately triggered the exception.

```suggestion
            raise InvalidRequirement from e
```

2022-12-07 21:50 UTC, closed without merging