test: Expand testing for wheel multi-version multi-platform
pypa/packaging pull request #608
Opened 2022-11-07 17:29 UTC by jacobdr

Following this [past week's issue](https://pypi.org/project/wheel/#history) with `wheel==0.38`, this adds slightly more testing. While its somewhat duplicative of what might already be tested in `test_tags.py`, since this is the most natural palce to put an "end-user" consumption test (viz the internals), I thought the juice was worth the squeeze as a defensive test.

I submitted a PR with similar testing to the `wheel` package via https://github.com/pypa/wheel/pull/486, but since the intention is to have `wheel` depend on `packaging` eventually, I also wanted to make a similar contribution here.

* Add slightly more testing to the wheel and sdist tests
* Add venv to the .gitignore

2022-11-09 00:34 UTC, brettcannon requested changes

2022-11-09 00:34 UTC, brettcannon commented on tests/test_utils.py
> +    """
```suggestion
    # See https://peps.python.org/pep-0625/#specification for the spec.
```

2022-11-09 22:44 UTC, jacobdr commented on .gitignore
> +venv
the habits we developer over the years. I can wildcard the front if you want to everyone is a winner 🧨  -- I think you get the general point

2022-11-15 00:05 UTC, brettcannon commented on .gitignore
> +venv
I was mostly curious as the dev lead for the Python extension for VS Code.

2022-11-15 00:05 UTC, brettcannon commented
@jacobdr please refresh my review when you're ready for me to have another look.

2026-07-21 16:50 UTC, henryiii commented
Most of this is now tested, but the multi one is still useful. I reduced it to just that.

2026-07-21 17:50 UTC, merged