Remove URL validation from requirement parsing
pypa/packaging pull request #684
Opened 2023-03-30 08:51 UTC by uranusjr

The scheme and path validation logic limits how users of the library can provide URL support. This limitation is lifted, and dependants now need to implement their own URL validation logic they see fit.

Close #120.

2023-03-31 20:16 UTC, brettcannon requested changes
Should probably update the docs saying that this is no longer being done.

2023-04-13 07:10 UTC, uranusjr commented
Documentation and changelog added.

2023-04-13 07:20 UTC, sbidoul approved these changes

2023-04-13 16:11 UTC, pradyunsg approved these changes

2023-06-09 22:33 UTC, brettcannon approved these changes

2023-06-09 22:34 UTC, brettcannon commented
@pradyunsg is your "pause" still on, or are you okay with this change?

2023-06-11 10:29 UTC, pradyunsg approved these changes
Let's do this.

2023-06-13 18:24 UTC, merged