Update copyright date for docs
pypa/packaging pull request #713
Opened 2023-08-28 16:52 UTC by garrypolley

Updating copyright date for docs so readers will more easily be able to tell updates have happened in recent years.

2023-08-28 22:29 UTC, brettcannon commented
I honestly think we should ditch the end date as I believe it isn't necessary for copyright enforcement and having to update it every year seems like busy work.

@pradyunsg thoughts?

2023-09-02 00:14 UTC, pradyunsg commented
I agree. Let's drop the `-2019` (or, I guess, `-2023`).

2023-09-02 00:34 UTC, brettcannon requested changes

2023-09-02 00:34 UTC, brettcannon commented on src/packaging/__init__.py
> +__copyright__ = "2014-2023 %s" % __author__
```suggestion
__copyright__ = "2014 %s" % __author__
```

2023-09-02 10:33 UTC, pradyunsg approved these changes

2023-09-06 00:05 UTC, brettcannon approved these changes

2023-09-06 00:22 UTC, merged